version: "3"
services:
  app1:
    build: 
      context: .  # Specifies the directory where Docker will look for the Dockerfile.
      dockerfile: Dockerfile-index  # Specifies the file Docker will use in that directory.
    ports:
      - "4000:4000"
    depends_on:
      - mongodb

  app2:
    build: 
      context: .
      dockerfile: Dockerfile-server
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
